#!/usr/bin/expect

if {$env(ELECTRUM_NETWORK) eq ""} {
  spawn electrum -D "$env(ELECTRUM_PATH)" create
} else {
  spawn electrum "$env(ELECTRUM_NETWORK)" -D "$env(ELECTRUM_PATH)" create
}

expect -exact "Password (hit return if you do not wish to encrypt your wallet):"
send -- "$env(ELECTRUM_WALLET_PASSWORD)\r"

if {$env(ELECTRUM_WALLET_PASSWORD) eq ""} {
 
} else {
    expect -exact "Confirm:"
    send -- "$env(ELECTRUM_WALLET_PASSWORD)\r"
}

expect eof
